----> Institution

/*1*/insert into institution values (default, 'Universidad Central', '860.024.746-1', '@ucentral.edu.co');
/*2*/insert into institution values (default, 'Universidad de Bogotá Jorge Tadeo Lozano', '860.006.848-6', '@utadeo.edu.co');

-----> collection

/*1*/insert into collection values (default, 'CIAA-UJTL', 2);

-----> catalog

/*1*/insert into catalog values (default, 'Hym50', 1);
/*2*/insert into catalog values (default, 'Hym66', 1);
/*3*/insert into catalog values (default, 'Hym376', 1);
/*4*/insert into catalog values (default, 'Lep17', 1);
/*5*/insert into catalog values (default, 'Lep20', 1);
/*6*/insert into catalog values (default, 'D353', 1);

-----> sample_type

insert into sample_type values (default, 'Ejemplar Completo (ETOH)');

-----> reg_type

insert into reg_type values (default, 'Espécimen Preservado');

-----> author

/*1*/insert into author values (default, 'Hernández L.', 1, 1, 1, null);
/*2*/insert into author values (default, 'Carrillo D.', 1, 0, 1,  null);
/*3*/insert into author values (default, 'Ortiz G.', 1, 0, 0,  null);
/*4*/insert into author values (default, 'Jiménez T.', 0, 0, 1,  null);
/*5*/insert into author values (default, 'Pérez M.', 0, 0, 1,  null);

----> location level

/*1*/insert into location_level values (default, 'País', 0);
/*2*/insert into location_level values (default, 'Departamento', 1);
/*3*/insert into location_level values (default, 'Municipio', 2);
/*4*/insert into location_level values (default, 'Localidad', 3);

----> Location

insert into location values(default, 'Colombia', 0, 0, 0, 0, 1, null);
insert into location values (default,'Amazonas', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Antioquia', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Arauca', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Archipiélago de San Andrés, Providencia y Santa Catalina', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Atlántico', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Bogotá, D.C.', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Bolívar', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Boyacá', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Caldas', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Caquetá', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Casanare', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Cauca', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Cesar', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Chocó', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Córdoba', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Cundinamarca', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Guainía', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Guaviare', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Huila', 0, 0, 0, 0, 2, 1);
insert into location values (default,'La Guajira', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Magdalena', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Meta', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Nariño', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Norte de Santander', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Putumayo', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Quindio', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Risaralda', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Santander', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Sucre', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Tolima', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Valle del Cauca', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Vaupés', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Vichada', 0, 0, 0, 0, 2, 1);
insert into location values (default,'Cañasgordas', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Medellín', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Cáceres', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Campamento', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Abejorral', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Abriaquí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Alejandría', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Amagá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Amalfi', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Andes', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Caicedo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Angelópolis', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Angostura', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Anzá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Anorí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Santa Fé de Antioquia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Caracolí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Caramanta', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Apartadó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Arboletes', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Argelia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Armenia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Barbosa', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Belmira', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Caldas', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Bello', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Betania', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Betulia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Ciudad Bolívar', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Briceño', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Buriticá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Carepa', 0, 0, 0, 0, 3, 3);
insert into location values (default,'El Carmen de Viboral', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Carolina', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Caucasia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Chigorodó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Cisneros', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Cocorná', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Concepción', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Concordia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Copacabana', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Dabeiba', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Donmatías', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Ebéjico', 0, 0, 0, 0, 3, 3);
insert into location values (default,'El Bagre', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Entrerríos', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Envigado', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Fredonia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Frontino', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Giraldo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Girardota', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Gómez Plata', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Granada', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Guadalupe', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Guarne', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Guatapé', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Heliconia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Hispania', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Itagüí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Ituango', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Jardín', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Jericó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'La Ceja', 0, 0, 0, 0, 3, 3);
insert into location values (default,'La Estrella', 0, 0, 0, 0, 3, 3);
insert into location values (default,'La Pintada', 0, 0, 0, 0, 3, 3);
insert into location values (default,'La Unión', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Liborina', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Maceo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Marinilla', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Montebello', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Murindó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Mutatá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Nariño', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Necoclí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Nechí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Olaya', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Peñol', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Peque', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Pueblorrico', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Puerto Berrío', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Puerto Nare', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Puerto Triunfo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Remedios', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Retiro', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Rionegro', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Sabanalarga', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Sabaneta', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Salgar', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Andrés de Cuerquía', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Carlos', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Francisco', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Jerónimo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San José de La Montaña', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Juan de Urabá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Luis', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Pedro de Los Milagros', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Pedro de Urabá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Rafael', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Roque', 0, 0, 0, 0, 3, 3);
insert into location values (default,'San Vicente Ferrer', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Santa Bárbara', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Santa Rosa de Osos', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Santo Domingo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'El Santuario', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Segovia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Sonsón', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Sopetrán', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Támesis', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Tarazá', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Tarso', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Titiribí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Toledo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Turbo', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Uramita', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Urrao', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Valdivia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Valparaíso', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Vegachí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Venecia', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Vigía del Fuerte', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Yalí', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Yarumal', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Yolombó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Yondó', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Zaragoza', 0, 0, 0, 0, 3, 3);
insert into location values (default,'Barranquilla', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Baranoa', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Campo de La Cruz', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Candelaria', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Galapa', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Juan de Acosta', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Luruaco', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Malambo', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Manatí', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Palmar de Varela', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Piojó', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Polonuevo', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Ponedera', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Puerto Colombia', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Repelón', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Sabanagrande', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Sabanalarga', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Santa Lucía', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Santo Tomás', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Soledad', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Suan', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Tubará', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Usiacurí', 0, 0, 0, 0, 3, 6);
insert into location values (default,'Bogotá, D.C.', 0, 0, 0, 0, 3, 7);
insert into location values (default,'Cartagena de Indias', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Achí', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Altos del Rosario', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Arenal', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Arjona', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Arroyohondo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Barranco de Loba', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Calamar', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Cantagallo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Cicuco', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Córdoba', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Clemencia', 0, 0, 0, 0, 3, 8);
insert into location values (default,'El Carmen de Bolívar', 0, 0, 0, 0, 3, 8);
insert into location values (default,'El Guamo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'El Peñón', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Hatillo de Loba', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Magangué', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Mahates', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Margarita', 0, 0, 0, 0, 3, 8);
insert into location values (default,'María La Baja', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Montecristo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Mompós', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Morales', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Norosí', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Pinillos', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Regidor', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Río Viejo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Cristóbal', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Estanislao', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Fernando', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Jacinto', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Jacinto del Cauca', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Juan Nepomuceno', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Martín de Loba', 0, 0, 0, 0, 3, 8);
insert into location values (default,'San Pablo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Santa Catalina', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Santa Rosa', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Santa Rosa del Sur', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Simití', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Soplaviento', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Talaigua Nuevo', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Tiquisio', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Turbaco', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Turbaná', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Villanueva', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Zambrano', 0, 0, 0, 0, 3, 8);
insert into location values (default,'Tunja', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Almeida', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Aquitania', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Arcabuco', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Belén', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Berbeo', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Betéitiva', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Boavita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Boyacá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Briceño', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Buenavista', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Busbanzá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Caldas', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Campohermoso', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Cerinza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chinavita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chiquinquirá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chiscas', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chitaraque', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chivatá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Ciénega', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Cómbita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Coper', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Corrales', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Covarachía', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Cubará', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Cucaita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Cuítiva', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chíquiza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Chivor', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Duitama', 0, 0, 0, 0, 3, 9);
insert into location values (default,'El Cocuy', 0, 0, 0, 0, 3, 9);
insert into location values (default,'El Espino', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Firavitoba', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Floresta', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Gachantivá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Gámeza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Garagoa', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Guacamayas', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Guateque', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Guayatá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Güicán', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Iza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Jenesano', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Jericó', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Labranzagrande', 0, 0, 0, 0, 3, 9);
insert into location values (default,'La Capilla', 0, 0, 0, 0, 3, 9);
insert into location values (default,'La Victoria', 0, 0, 0, 0, 3, 9);
insert into location values (default,'La Uvita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Villa de Leyva', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Macanal', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Maripí', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Miraflores', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Mongua', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Monguí', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Moniquirá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Motavita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Muzo', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Nobsa', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Nuevo Colón', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Oicatá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Otanche', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Pachavita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Páez', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Paipa', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Pajarito', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Panqueba', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Pauna', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Paya', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Paz de Río', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Pesca', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Pisba', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Puerto Boyacá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Quípama', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Ramiriquí', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Ráquira', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Rondón', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Saboyá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sáchica', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Samacá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San Eduardo', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San José de Pare', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San Luis de Gaceno', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San Mateo', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San Miguel de Sema', 0, 0, 0, 0, 3, 9);
insert into location values (default,'San Pablo de Borbur', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Santana', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Santa María', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Santa Rosa de Viterbo', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Santa Sofía', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sativanorte', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sativasur', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Siachoque', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Soatá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Socotá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Socha', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sogamoso', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Somondoco', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sora', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sotaquirá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Soracá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Susacón', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sutamarchán', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Sutatenza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tasco', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tenza', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tibaná', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tibasosa', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tinjacá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tipacoque', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Toca', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Togüí', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tópaga', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tota', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tununguá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Turmequé', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tuta', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Tutazá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Úmbita', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Ventaquemada', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Viracachá', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Zetaquira', 0, 0, 0, 0, 3, 9);
insert into location values (default,'Manizales', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Aguadas', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Anserma', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Aranzazu', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Belalcázar', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Chinchiná', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Filadelfia', 0, 0, 0, 0, 3, 10);
insert into location values (default,'La Dorada', 0, 0, 0, 0, 3, 10);
insert into location values (default,'La Merced', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Manzanares', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Marmato', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Marquetalia', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Marulanda', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Neira', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Norcasia', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Pácora', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Palestina', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Pensilvania', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Riosucio', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Risaralda', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Salamina', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Samaná', 0, 0, 0, 0, 3, 10);
insert into location values (default,'San José', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Supía', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Victoria', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Villamaría', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Viterbo', 0, 0, 0, 0, 3, 10);
insert into location values (default,'Florencia', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Albania', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Belén de Los Andaquíes', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Cartagena del Chairá', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Curillo', 0, 0, 0, 0, 3, 11);
insert into location values (default,'El Doncello', 0, 0, 0, 0, 3, 11);
insert into location values (default,'El Paujíl', 0, 0, 0, 0, 3, 11);
insert into location values (default,'La Montañita', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Milán', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Morelia', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Puerto Rico', 0, 0, 0, 0, 3, 11);
insert into location values (default,'San José del Fragua', 0, 0, 0, 0, 3, 11);
insert into location values (default,'San Vicente del Caguán', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Solano', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Solita', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Valparaíso', 0, 0, 0, 0, 3, 11);
insert into location values (default,'Popayán', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Almaguer', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Argelia', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Balboa', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Bolívar', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Buenos Aires', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Cajibío', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Caldono', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Caloto', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Corinto', 0, 0, 0, 0, 3, 13);
insert into location values (default,'El Tambo', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Florencia', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Guachené', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Guapí', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Inzá', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Jambaló', 0, 0, 0, 0, 3, 13);
insert into location values (default,'La Sierra', 0, 0, 0, 0, 3, 13);
insert into location values (default,'La Vega', 0, 0, 0, 0, 3, 13);
insert into location values (default,'López de Micay', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Mercaderes', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Miranda', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Morales', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Padilla', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Páez', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Patía', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Piamonte', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Piendamó', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Puerto Tejada', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Puracé', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Rosas', 0, 0, 0, 0, 3, 13);
insert into location values (default,'San Sebastián', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Santander de Quilichao', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Santa Rosa', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Silvia', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Sotara', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Suárez', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Sucre', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Timbío', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Timbiquí', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Toribío', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Totoró', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Villa Rica', 0, 0, 0, 0, 3, 13);
insert into location values (default,'Valledupar', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Aguachica', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Agustín Codazzi', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Astrea', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Becerril', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Bosconia', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Chimichagua', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Chiriguaná', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Curumaní', 0, 0, 0, 0, 3, 14);
insert into location values (default,'El Copey', 0, 0, 0, 0, 3, 14);
insert into location values (default,'El Paso', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Gamarra', 0, 0, 0, 0, 3, 14);
insert into location values (default,'González', 0, 0, 0, 0, 3, 14);
insert into location values (default,'La Gloria', 0, 0, 0, 0, 3, 14);
insert into location values (default,'La Jagua de Ibirico', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Manaure Balcón del Cesar', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Pailitas', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Pelaya', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Pueblo Bello', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Río de Oro', 0, 0, 0, 0, 3, 14);
insert into location values (default,'La Paz', 0, 0, 0, 0, 3, 14);
insert into location values (default,'San Alberto', 0, 0, 0, 0, 3, 14);
insert into location values (default,'San Diego', 0, 0, 0, 0, 3, 14);
insert into location values (default,'San Martín', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Tamalameque', 0, 0, 0, 0, 3, 14);
insert into location values (default,'Montería', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Ayapel', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Buenavista', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Canalete', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Cereté', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Chimá', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Chinú', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Ciénaga de Oro', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Cotorra', 0, 0, 0, 0, 3, 16);
insert into location values (default,'La Apartada', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Lorica', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Los Córdobas', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Momil', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Montelíbano', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Moñitos', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Planeta Rica', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Pueblo Nuevo', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Puerto Escondido', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Puerto Libertador', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Purísima de La Concepción', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Sahagún', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San Andrés de Sotavento', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San Antero', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San Bernardo del Viento', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San Carlos', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San José de Uré', 0, 0, 0, 0, 3, 16);
insert into location values (default,'San Pelayo', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Tierralta', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Tuchín', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Valencia', 0, 0, 0, 0, 3, 16);
insert into location values (default,'Agua de Dios', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Albán', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Anapoima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Anolaima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Arbeláez', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Beltrán', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Bituima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Bojacá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cabrera', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cachipay', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cajicá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Caparrapí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cáqueza', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Carmen de Carupa', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Chaguaní', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Chía', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Chipaque', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Choachí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Chocontá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cogua', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cota', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Cucunubá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'El Colegio', 0, 0, 0, 0, 3, 17);
insert into location values (default,'El Peñón', 0, 0, 0, 0, 3, 17);
insert into location values (default,'El Rosal', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Facatativá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Fómeque', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Fosca', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Funza', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Fúquene', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Fusagasugá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Gachalá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Gachancipá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Gachetá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Gama', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Girardot', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Granada', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guachetá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guaduas', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guasca', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guataquí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guatavita', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guayabal de Síquima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Guayabetal', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Gutiérrez', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Jerusalén', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Junín', 0, 0, 0, 0, 3, 17);
insert into location values (default,'La Calera', 0, 0, 0, 0, 3, 17);
insert into location values (default,'La Mesa', 0, 0, 0, 0, 3, 17);
insert into location values (default,'La Palma', 0, 0, 0, 0, 3, 17);
insert into location values (default,'La Peña', 0, 0, 0, 0, 3, 17);
insert into location values (default,'La Vega', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Lenguazaque', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Machetá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Madrid', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Manta', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Medina', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Mosquera', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Nariño', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Nemocón', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Nilo', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Nimaima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Nocaima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Venecia', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Pacho', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Paime', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Pandi', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Paratebueno', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Pasca', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Puerto Salgar', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Pulí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Quebradanegra', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Quetame', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Quipile', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Apulo', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Ricaurte', 0, 0, 0, 0, 3, 17);
insert into location values (default,'San Antonio del Tequendama', 0, 0, 0, 0, 3, 17);
insert into location values (default,'San Bernardo', 0, 0, 0, 0, 3, 17);
insert into location values (default,'San Cayetano', 0, 0, 0, 0, 3, 17);
insert into location values (default,'San Francisco', 0, 0, 0, 0, 3, 17);
insert into location values (default,'San Juan de Rioseco', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Sasaima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Sesquilé', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Sibaté', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Silvania', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Simijaca', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Soacha', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Sopó', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Subachoque', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Suesca', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Supatá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Susa', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Sutatausa', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tabio', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tausa', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tena', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tenjo', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tibacuy', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tibirita', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tocaima', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Tocancipá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Topaipí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Ubalá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Ubaque', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Villa de San Diego de Ubaté', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Une', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Útica', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Vergara', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Vianí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Villagómez', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Villapinzón', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Villeta', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Viotá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Yacopí', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Zipacón', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Zipaquirá', 0, 0, 0, 0, 3, 17);
insert into location values (default,'Quibdó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Acandí', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Alto Baudó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Atrato', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Bagadó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Bahía Solano', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Bajo Baudó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Bojayá', 0, 0, 0, 0, 3, 15);
insert into location values (default,'El Cantón del San Pablo', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Carmen del Darién', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Cértegui', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Condoto', 0, 0, 0, 0, 3, 15);
insert into location values (default,'El Carmen de Atrato', 0, 0, 0, 0, 3, 15);
insert into location values (default,'El Litoral del San Juan', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Istmina', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Juradó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Lloró', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Medio Atrato', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Medio Baudó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Medio San Juan', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Nóvita', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Nuquí', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Río Iró', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Río Quito', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Riosucio', 0, 0, 0, 0, 3, 15);
insert into location values (default,'San José del Palmar', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Sipí', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Tadó', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Unguía', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Unión Panamericana', 0, 0, 0, 0, 3, 15);
insert into location values (default,'Neiva', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Acevedo', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Agrado', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Aipe', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Algeciras', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Altamira', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Baraya', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Campoalegre', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Colombia', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Elías', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Garzón', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Gigante', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Guadalupe', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Hobo', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Íquira', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Isnos', 0, 0, 0, 0, 3, 20);
insert into location values (default,'La Argentina', 0, 0, 0, 0, 3, 20);
insert into location values (default,'La Plata', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Nátaga', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Oporapa', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Paicol', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Palermo', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Palestina', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Pital', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Pitalito', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Rivera', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Saladoblanco', 0, 0, 0, 0, 3, 20);
insert into location values (default,'San Agustín', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Santa María', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Suaza', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Tarqui', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Tesalia', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Tello', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Teruel', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Timaná', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Villavieja', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Yaguará', 0, 0, 0, 0, 3, 20);
insert into location values (default,'Riohacha', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Albania', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Barrancas', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Dibulla', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Distracción', 0, 0, 0, 0, 3, 21);
insert into location values (default,'El Molino', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Fonseca', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Hatonuevo', 0, 0, 0, 0, 3, 21);
insert into location values (default,'La Jagua del Pilar', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Maicao', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Manaure', 0, 0, 0, 0, 3, 21);
insert into location values (default,'San Juan del Cesar', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Uribia', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Urumita', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Villanueva', 0, 0, 0, 0, 3, 21);
insert into location values (default,'Santa Marta', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Algarrobo', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Aracataca', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Ariguaní', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Cerro de San Antonio', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Chivolo', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Ciénaga', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Concordia', 0, 0, 0, 0, 3, 22);
insert into location values (default,'El Banco', 0, 0, 0, 0, 3, 22);
insert into location values (default,'El Piñón', 0, 0, 0, 0, 3, 22);
insert into location values (default,'El Retén', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Fundación', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Guamal', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Nueva Granada', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Pedraza', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Pijiño del Carmen', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Pivijay', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Plato', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Puebloviejo', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Remolino', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Sabanas de San Ángel', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Salamina', 0, 0, 0, 0, 3, 22);
insert into location values (default,'San Sebastián de Buenavista', 0, 0, 0, 0, 3, 22);
insert into location values (default,'San Zenón', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Santa Ana', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Santa Bárbara de Pinto', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Sitionuevo', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Tenerife', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Zapayán', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Zona Bananera', 0, 0, 0, 0, 3, 22);
insert into location values (default,'Villavicencio', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Acacías', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Barranca de Upía', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Cabuyaro', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Castilla La Nueva', 0, 0, 0, 0, 3, 23);
insert into location values (default,'San Luis de Cubarral', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Cumaral', 0, 0, 0, 0, 3, 23);
insert into location values (default,'El Calvario', 0, 0, 0, 0, 3, 23);
insert into location values (default,'El Castillo', 0, 0, 0, 0, 3, 23);
insert into location values (default,'El Dorado', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Fuente de Oro', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Granada', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Guamal', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Mapiripán', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Mesetas', 0, 0, 0, 0, 3, 23);
insert into location values (default,'La Macarena', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Uribe', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Lejanías', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Puerto Concordia', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Puerto Gaitán', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Puerto López', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Puerto Lleras', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Puerto Rico', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Restrepo', 0, 0, 0, 0, 3, 23);
insert into location values (default,'San Carlos de Guaroa', 0, 0, 0, 0, 3, 23);
insert into location values (default,'San Juan de Arama', 0, 0, 0, 0, 3, 23);
insert into location values (default,'San Juanito', 0, 0, 0, 0, 3, 23);
insert into location values (default,'San Martín', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Vistahermosa', 0, 0, 0, 0, 3, 23);
insert into location values (default,'Pasto', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Albán', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Aldana', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Ancuyá', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Arboleda', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Barbacoas', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Belén', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Buesaco', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Colón', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Consacá', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Contadero', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Córdoba', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Cuaspúd', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Cumbal', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Cumbitara', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Chachagüí', 0, 0, 0, 0, 3, 24);
insert into location values (default,'El Charco', 0, 0, 0, 0, 3, 24);
insert into location values (default,'El Peñol', 0, 0, 0, 0, 3, 24);
insert into location values (default,'El Rosario', 0, 0, 0, 0, 3, 24);
insert into location values (default,'El Tablón de Gómez', 0, 0, 0, 0, 3, 24);
insert into location values (default,'El Tambo', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Funes', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Guachucal', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Guaitarilla', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Gualmatán', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Iles', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Imués', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Ipiales', 0, 0, 0, 0, 3, 24);
insert into location values (default,'La Cruz', 0, 0, 0, 0, 3, 24);
insert into location values (default,'La Florida', 0, 0, 0, 0, 3, 24);
insert into location values (default,'La Llanada', 0, 0, 0, 0, 3, 24);
insert into location values (default,'La Tola', 0, 0, 0, 0, 3, 24);
insert into location values (default,'La Unión', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Leiva', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Linares', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Los Andes', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Magüí', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Mallama', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Mosquera', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Nariño', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Olaya Herrera', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Ospina', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Francisco Pizarro', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Policarpa', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Potosí', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Providencia', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Puerres', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Pupiales', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Ricaurte', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Roberto Payán', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Samaniego', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Sandoná', 0, 0, 0, 0, 3, 24);
insert into location values (default,'San Bernardo', 0, 0, 0, 0, 3, 24);
insert into location values (default,'San Lorenzo', 0, 0, 0, 0, 3, 24);
insert into location values (default,'San Pablo', 0, 0, 0, 0, 3, 24);
insert into location values (default,'San Pedro de Cartago', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Santa Bárbara', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Santacruz', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Sapuyes', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Taminango', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Tangua', 0, 0, 0, 0, 3, 24);
insert into location values (default,'San Andrés de Tumaco', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Túquerres', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Yacuanquer', 0, 0, 0, 0, 3, 24);
insert into location values (default,'Cúcuta', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Ábrego', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Arboledas', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Bochalema', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Bucarasica', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Cácota', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Cáchira', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Chinácota', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Chitagá', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Convención', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Cucutilla', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Durania', 0, 0, 0, 0, 3, 25);
insert into location values (default,'El Carmen', 0, 0, 0, 0, 3, 25);
insert into location values (default,'El Tarra', 0, 0, 0, 0, 3, 25);
insert into location values (default,'El Zulia', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Gramalote', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Hacarí', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Herrán', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Labateca', 0, 0, 0, 0, 3, 25);
insert into location values (default,'La Esperanza', 0, 0, 0, 0, 3, 25);
insert into location values (default,'La Playa', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Los Patios', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Lourdes', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Mutiscua', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Ocaña', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Pamplona', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Pamplonita', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Puerto Santander', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Ragonvalia', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Salazar', 0, 0, 0, 0, 3, 25);
insert into location values (default,'San Calixto', 0, 0, 0, 0, 3, 25);
insert into location values (default,'San Cayetano', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Santiago', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Sardinata', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Silos', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Teorama', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Tibú', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Toledo', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Villa Caro', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Villa del Rosario', 0, 0, 0, 0, 3, 25);
insert into location values (default,'Armenia', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Buenavista', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Calarcá', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Circasia', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Córdoba', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Filandia', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Génova', 0, 0, 0, 0, 3, 27);
insert into location values (default,'La Tebaida', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Montenegro', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Pijao', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Quimbaya', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Salento', 0, 0, 0, 0, 3, 27);
insert into location values (default,'Pereira', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Apía', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Balboa', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Belén de Umbría', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Dosquebradas', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Guática', 0, 0, 0, 0, 3, 28);
insert into location values (default,'La Celia', 0, 0, 0, 0, 3, 28);
insert into location values (default,'La Virginia', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Marsella', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Mistrató', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Pueblo Rico', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Quinchía', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Santa Rosa de Cabal', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Santuario', 0, 0, 0, 0, 3, 28);
insert into location values (default,'Bucaramanga', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Aguada', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Albania', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Aratoca', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Barbosa', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Barichara', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Barrancabermeja', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Betulia', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Bolívar', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Cabrera', 0, 0, 0, 0, 3, 29);
insert into location values (default,'California', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Capitanejo', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Carcasí', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Cepitá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Cerrito', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Charalá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Charta', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Chima', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Chipatá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Cimitarra', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Concepción', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Confines', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Contratación', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Coromoro', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Curití', 0, 0, 0, 0, 3, 29);
insert into location values (default,'El Carmen de Chucurí', 0, 0, 0, 0, 3, 29);
insert into location values (default,'El Guacamayo', 0, 0, 0, 0, 3, 29);
insert into location values (default,'El Peñón', 0, 0, 0, 0, 3, 29);
insert into location values (default,'El Playón', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Encino', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Enciso', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Florián', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Floridablanca', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Galán', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Gámbita', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Girón', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Guaca', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Guadalupe', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Guapotá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Guavatá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Güepsa', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Hato', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Jesús María', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Jordán', 0, 0, 0, 0, 3, 29);
insert into location values (default,'La Belleza', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Landázuri', 0, 0, 0, 0, 3, 29);
insert into location values (default,'La Paz', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Lebrija', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Los Santos', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Macaravita', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Málaga', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Matanza', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Mogotes', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Molagavita', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Ocamonte', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Oiba', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Onzaga', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Palmar', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Palmas del Socorro', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Páramo', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Piedecuesta', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Pinchote', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Puente Nacional', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Puerto Parra', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Puerto Wilches', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Rionegro', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Sabana de Torres', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Andrés', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Benito', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Gil', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Joaquín', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San José de Miranda', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Miguel', 0, 0, 0, 0, 3, 29);
insert into location values (default,'San Vicente de Chucurí', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Santa Bárbara', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Santa Helena del Opón', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Simacota', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Socorro', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Suaita', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Sucre', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Suratá', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Tona', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Valle de San José', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Vélez', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Vetas', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Villanueva', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Zapatoca', 0, 0, 0, 0, 3, 29);
insert into location values (default,'Sincelejo', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Buenavista', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Caimito', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Coloso', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Corozal', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Coveñas', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Chalán', 0, 0, 0, 0, 3, 30);
insert into location values (default,'El Roble', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Galeras', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Guaranda', 0, 0, 0, 0, 3, 30);
insert into location values (default,'La Unión', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Los Palmitos', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Majagual', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Morroa', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Ovejas', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Palmito', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Sampués', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Benito Abad', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Juan de Betulia', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Marcos', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Onofre', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Pedro', 0, 0, 0, 0, 3, 30);
insert into location values (default,'San Luis de Sincé', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Sucre', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Santiago de Tolú', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Tolú Viejo', 0, 0, 0, 0, 3, 30);
insert into location values (default,'Ibagué', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Alpujarra', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Alvarado', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Ambalema', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Anzoátegui', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Armero Guayabal', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Ataco', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Cajamarca', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Carmen de Apicalá', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Casabianca', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Chaparral', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Coello', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Coyaima', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Cunday', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Dolores', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Espinal', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Falan', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Flandes', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Fresno', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Guamo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Herveo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Honda', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Icononzo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Lérida', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Líbano', 0, 0, 0, 0, 3, 31);
insert into location values (default,'San Sebastián de Mariquita', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Melgar', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Murillo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Natagaima', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Ortega', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Palocabildo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Piedras', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Planadas', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Prado', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Purificación', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Rioblanco', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Roncesvalles', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Rovira', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Saldaña', 0, 0, 0, 0, 3, 31);
insert into location values (default,'San Antonio', 0, 0, 0, 0, 3, 31);
insert into location values (default,'San Luis', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Santa Isabel', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Suárez', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Valle de San Juan', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Venadillo', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Villahermosa', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Villarrica', 0, 0, 0, 0, 3, 31);
insert into location values (default,'Cali', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Alcalá', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Andalucía', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Ansermanuevo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Argelia', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Bolívar', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Buenaventura', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Guadalajara de Buga', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Bugalagrande', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Caicedonia', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Calima', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Candelaria', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Cartago', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Dagua', 0, 0, 0, 0, 3, 32);
insert into location values (default,'El Águila', 0, 0, 0, 0, 3, 32);
insert into location values (default,'El Cairo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'El Cerrito', 0, 0, 0, 0, 3, 32);
insert into location values (default,'El Dovio', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Florida', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Ginebra', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Guacarí', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Jamundí', 0, 0, 0, 0, 3, 32);
insert into location values (default,'La Cumbre', 0, 0, 0, 0, 3, 32);
insert into location values (default,'La Unión', 0, 0, 0, 0, 3, 32);
insert into location values (default,'La Victoria', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Obando', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Palmira', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Pradera', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Restrepo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Riofrío', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Roldanillo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'San Pedro', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Sevilla', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Toro', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Trujillo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Tuluá', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Ulloa', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Versalles', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Vijes', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Yotoco', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Yumbo', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Zarzal', 0, 0, 0, 0, 3, 32);
insert into location values (default,'Arauca', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Arauquita', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Cravo Norte', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Fortul', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Puerto Rondón', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Saravena', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Tame', 0, 0, 0, 0, 3, 4);
insert into location values (default,'Yopal', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Aguazul', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Chámeza', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Hato Corozal', 0, 0, 0, 0, 3, 12);
insert into location values (default,'La Salina', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Maní', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Monterrey', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Nunchía', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Orocué', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Paz de Ariporo', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Pore', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Recetor', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Sabanalarga', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Sácama', 0, 0, 0, 0, 3, 12);
insert into location values (default,'San Luis de Palenque', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Támara', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Tauramena', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Trinidad', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Villanueva', 0, 0, 0, 0, 3, 12);
insert into location values (default,'Mocoa', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Colón', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Orito', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Puerto Asís', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Puerto Caicedo', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Puerto Guzmán', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Puerto Leguízamo', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Sibundoy', 0, 0, 0, 0, 3, 26);
insert into location values (default,'San Francisco', 0, 0, 0, 0, 3, 26);
insert into location values (default,'San Miguel', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Santiago', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Valle del Guamuez', 0, 0, 0, 0, 3, 26);
insert into location values (default,'Villagarzón', 0, 0, 0, 0, 3, 26);
insert into location values (default,'San Andrés', 0, 0, 0, 0, 3, 5);
insert into location values (default,'Providencia', 0, 0, 0, 0, 3, 5);
insert into location values (default,'Leticia', 0, 0, 0, 0, 3, 2);
insert into location values (default,'El Encanto', 0, 0, 0, 0, 3, 2);
insert into location values (default,'La Chorrera', 0, 0, 0, 0, 3, 2);
insert into location values (default,'La Pedrera', 0, 0, 0, 0, 3, 2);
insert into location values (default,'La Victoria', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Mirití - Paraná', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Puerto Alegría', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Puerto Arica', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Puerto Nariño', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Puerto Santander', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Tarapacá', 0, 0, 0, 0, 3, 2);
insert into location values (default,'Inírida', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Barranco Minas', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Mapiripana', 0, 0, 0, 0, 3, 18);
insert into location values (default,'San Felipe', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Puerto Colombia', 0, 0, 0, 0, 3, 18);
insert into location values (default,'La Guadalupe', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Cacahual', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Pana Pana', 0, 0, 0, 0, 3, 18);
insert into location values (default,'Morichal', 0, 0, 0, 0, 3, 18);
insert into location values (default,'San José del Guaviare', 0, 0, 0, 0, 3, 19);
insert into location values (default,'Calamar', 0, 0, 0, 0, 3, 19);
insert into location values (default,'El Retorno', 0, 0, 0, 0, 3, 19);
insert into location values (default,'Miraflores', 0, 0, 0, 0, 3, 19);
insert into location values (default,'Mitú', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Carurú', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Pacoa', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Taraira', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Papunaua', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Yavaraté', 0, 0, 0, 0, 3, 33);
insert into location values (default,'Puerto Carreño', 0, 0, 0, 0, 3, 34);
insert into location values (default,'La Primavera', 0, 0, 0, 0, 3, 34);
insert into location values (default,'Santa Rosalía', 0, 0, 0, 0, 3, 34);
insert into location values (default,'Cumaribo', 0, 0, 0, 0, 3, 34);

insert into location values (default, 'Quebrada Calostros', 4.6794444, -73.7833333, 3452, 0, 4, 540);
insert into location values (default, 'Finca MG', 4.8636111, -74.0633333, 2562, 0, 4, 508);
insert into location values (default, 'Finca Jerusalén', 4.8333333, -75.0833333, 2547, 0, 4, 513);
insert into location values (default, 'Vereda Charo Centro', 7.0833333, -71, 186, 0, 4, 1087);
insert into location values (default, 'Finca San Ignacio', 4.8333333, -75.0833333, 2547, 0, 4, 513);

---> taxonomy_level

insert into taxonomy_level values (default, 'Reino', 0);
insert into taxonomy_level values (default, 'Superphylum', 1);
insert into taxonomy_level values (default, 'Phylum', 2);
insert into taxonomy_level values (default, 'Subphylum', 3);
insert into taxonomy_level values (default, 'Superclase', 4);
insert into taxonomy_level values (default, 'Clase', 5);
insert into taxonomy_level values (default, 'Subclase', 6);
insert into taxonomy_level values (default, 'Superorden', 7);
insert into taxonomy_level values (default, 'Orden', 8);
insert into taxonomy_level values (default, 'Suborden', 9);
insert into taxonomy_level values (default, 'Infraorden', 10);
insert into taxonomy_level values (default, 'Superfamilia', 11);
insert into taxonomy_level values (default, 'Familia', 12);
insert into taxonomy_level values (default, 'Subfamilia', 13);
insert into taxonomy_level values (default, 'Supertribu', 14);
insert into taxonomy_level values (default, 'Tribu', 15);
insert into taxonomy_level values (default, 'Subtribu', 16);
insert into taxonomy_level values (default, 'Supergenero', 17);
insert into taxonomy_level values (default, 'Genero', 18);
insert into taxonomy_level values (default, 'Subgenero', 19);
insert into taxonomy_level values (default, 'Superespecie', 20);
insert into taxonomy_level values (default, 'Especie', 21);
insert into taxonomy_level values (default, 'Subespecie', 22);

---> taxonomy

insert into taxonomy values (default, 'Animalia', 1, null);
insert into taxonomy values (default, 'Arthropoda', 3, 1);
insert into taxonomy values (default, 'Insecta', 6, 2);
insert into taxonomy values (default, 'Lepidoptera', 9, 3);
insert into taxonomy values (default, 'Ditrysa', 10, 4);
insert into taxonomy values (default, 'Apoditrysia', 11, 5);
insert into taxonomy values (default, 'Pterophoroidea', 12, 6);
insert into taxonomy values (default, 'Pterophoridae', 13, 7);
insert into taxonomy values (default, 'Pterophorinae', 14, 8);
insert into taxonomy values (default, 'Oidaematophorini', 16, 8);
insert into taxonomy values (default, 'Oidaematophorus', 19, 9);

insert into taxonomy values (default, 'Hymenoptera', 9, 3);
insert into taxonomy values (default, 'Apocrita', 10, 12);
insert into taxonomy values (default, 'Apoidea', 12, 13);
insert into taxonomy values (default, 'Apidae', 13, 14);
insert into taxonomy values (default, 'Apinae', 14, 15);
insert into taxonomy values (default, 'Apini', 16, 16);
insert into taxonomy values (default, 'Apis', 19, 17);

insert into taxonomy values (default, 'Vespoidea', 12, 13);
insert into taxonomy values (default, 'Vespidae', 13, 19);
insert into taxonomy values (default, 'Politinae', 14, 20);

insert into taxonomy values (default, 'Formicidae', 13, 19);

insert into taxonomy values (default, 'Diptera', 9, 3);
insert into taxonomy values (default, 'Brachycera', 10, 23);
insert into taxonomy values (default, 'Muscoidea', 12, 24);
insert into taxonomy values (default, 'Anthomyiidae', 13, 25);

----> users

/*1*/insert into users values (default, '1', 'Administrador', 'del Sistema', 'admin.cev@ucentral.edu.co', now(), now(), null, 'tBuvcpCBCU8feB6wPDZRpw==', 1);
/*1*/INSERT INTO USERS VALUES (DEFAULT, '2', 'Operador', '1', 'oper.cev@ucentral.edu.co', now(), now(), null, 'tBuvcpCBCU8feB6wPDZRpw==', 1);
-----> specimen

insert into specimen values(default, 'espelentesis', 'Polílla de Páramo', 11, 1, null , to_date('01/01/2013','dd/mm/yyyy'), 1, 1, 1157, 1, null, 'C-bios 1009', 5, to_date('10/12/2012','dd/mm/yyyy'), 'Colecta Directa', 1);
insert into specimen values(default, 'mellifera', 'Abeja de la Miel', 18, 5, null , to_date('01/01/2015','dd/mm/yyyy'), 1, 1, 1158, 3, null, 'C-bios 419', 2, to_date('12/02/1998','dd/mm/yyyy'), 'Colecta directa', 1);
insert into specimen values(default, null, 'Avispa Cintura de Oro', 21, 2, 'Sp5' , to_date('01/01/2015','dd/mm/yyyy'), 1, 1, 1159, 3, null, 'C-bios 403', 1, to_date('07/12/2004','dd/mm/yyyy'), 'En trampa Malaisse', 1);
insert into specimen values(default, null, 'Hormiga', 22, 4, null , to_date('01/01/2015','dd/mm/yyyy'), 1, 1, 1160, 2, null, 'C-bios 729', 3, to_date('12/08/2004','dd/mm/yyyy'), 'Trampa Pitfall', 1);
insert into specimen values(default, null, 'Mosco', 26, 2, null , to_date('01/01/2015','dd/mm/yyyy'), 1, 1, 1161, 2, null, 'C-bios 1008', 6, to_date('03/02/2005','dd/mm/yyyy'), 'Trampa Malaisse', 1);

-----> module

/*1*/insert into modules values (default, 'Gestión de Colecciones', 'Permite a los administradores estructurar los catálogos y las colecciones donde yacen los especímenes.', 1, null, null, null, null);
/*2*/insert into modules values (default, 'Gestión de Usuarios', 'Permite controlar y realizar seguimiento a los usuarios de la colección entomológica, además de cambiar y asignar roles de usuario (compuestos por accesos a la aplicación), nivel de acceso, cambio de credenciales e información del perfil.', 9, null, null, null, null);
/*3*/insert into modules values (default, 'Reporteador', 'Permite extraer estadísticos en listados de la información contenida en la colección así como el uso que se le da a esta, permitiendo su exportación.', 14, 'dummy.xhtml', 'pe-7s-display2', 'REPORTER', null);
/*4*/insert into modules values (default, 'Configuración', 'Permite definir algunas configuraciones del Centro Cntomológico Virtual.', 15, 'envConfig.xhtml', 'pe-7s-config', 'SETTINGS', null);

/*5*/insert into modules values (default, 'Asistente de Creación', 'Permite crear ejemplares en la colección.', 2, 'wizard.xhtml', 'pe-7s-plus', 'WIZARD', 1);
/*6*/insert into modules values (default, 'Clasificaciones', 'Permite realizar cambios en la lista de dominio de la clasificación taxonómica de manera jerárquica.', 3, 'taxonomy.xhtml', 'pe-7s-ticket', 'TAXONOMY', 1);
/*7*/insert into modules values (default, 'Ubicaciones', 'Permite realizar cambios en la lista de dominio de la ubicación de manera jerárquica.', 4, 'location.xhtml', 'pe-7s-map-marker', 'LOCATION', 1);
/*8*/insert into modules values (default, 'Autores', 'Permite definir los autores que recolectan y clasifican a los especímenes.', 5, 'author.xhtml', 'pe-7s-add-user', 'AUTHOR', 1);
/*9*/insert into modules values (default, 'Catálogos y Colecciones', 'Permite estructurar los catálogos y las colecciones donde yacen los especímenes.', 6, 'collections.xhtml', 'pe-7s-albums', 'COLLECTION', 1);
/*10*/insert into modules values (default, 'Especímenes', 'Permite incluir en la colección virtual los especímenes utilizando las listas de dominio definidas en los otros módulos.', 7, 'specimen.xhtml', 'pe-7s-magic-wand', 'SPECIMEN', 1);

/*11*/insert into modules values (default, 'Roles y Accesos', 'Permite a los usuarios administrar los roles y accesos.', 10, 'accesses.xhtml', 'pe-7s-id', 'ACCESSES', 2);
/*12*/insert into modules values (default, 'Credenciales', 'Permite a los usuarios cambiar las credenciales de acceso.', 11, 'dummy.xhtml', 'pe-7s-door-lock', 'CREDENTIALS', 2);
/*13*/insert into modules values (default, 'Auditoria', 'Este módulo permite conocer la auditoría realizada a los usuarios.', 12, 'dummy.xhtml', 'pe-7s-timer', 'AUDIT', 2);
/*14*/insert into modules values (default, 'Usuarios e Instituciones', 'Este módulo permite administrar a los usuarios.', 13, 'users.xhtml', 'pe-7s-users', 'USR_INS', 2);
/*15*/insert into modules values (default, 'Contenido Gráfico', 'Permite definir el contenido gráfico de los especímenes, tales como las imágenes de alta definición.', 8, 'specimenManager.xhtml', 'pe-7s-photo', 'CONTENT', 1);

-----> roles

/*1*/insert into roles values (default, 'Administrador del Sistema', 'Es un usuario con acceso a todos los módulos que componen el Sistema de gestión y navegación, además de modificar parámetros del sistema, administración de usuarios y perfiles.', now());
/*2*/insert into roles values (default, 'Administrador de Colección', 'Este usuario tiene el privilegio de construir y definir los datos de dominio que se usarán posteriormente para ingresar los especímenes individuales, y podrá definir la publicación de estos.', now());
/*3*/insert into roles values (default, 'Operario', 'Este usuario puede ingresar los especímenes a la colección utilizando los datos de dominio por parte del administrador de colección.', now());

-----> roles_modules

insert into roles_modules values (default, 1, 1, 15);
insert into roles_modules values (default, 1, 2, 15);
insert into roles_modules values (default, 1, 3, 15);
insert into roles_modules values (default, 1, 4, 15);
insert into roles_modules values (default, 1, 5, 15);
insert into roles_modules values (default, 1, 6, 15);
insert into roles_modules values (default, 1, 7, 15);
insert into roles_modules values (default, 1, 8, 15);
insert into roles_modules values (default, 1, 9, 15);
insert into roles_modules values (default, 1, 10, 15);
insert into roles_modules values (default, 1, 11, 15);
insert into roles_modules values (default, 1, 12, 15);
insert into roles_modules values (default, 1, 13, 15);
insert into roles_modules values (default, 1, 14, 15);
insert into roles_modules values (default, 1, 15, 15);

insert into roles_modules values (default, 2, 1, 15);
insert into roles_modules values (default, 2, 2, 15);
insert into roles_modules values (default, 2, 3, 15);
insert into roles_modules values (default, 2, 4, 15);
insert into roles_modules values (default, 2, 5, 15);
insert into roles_modules values (default, 2, 6, 15);
insert into roles_modules values (default, 2, 7, 15);
insert into roles_modules values (default, 2, 8, 15);
insert into roles_modules values (default, 2, 9, 15);
insert into roles_modules values (default, 2, 10, 15);
insert into roles_modules values (default, 2, 11, 15);
insert into roles_modules values (default, 2, 12, 15);
insert into roles_modules values (default, 2, 15, 15);

insert into roles_modules values (default, 3, 1, 15);
insert into roles_modules values (default, 3, 2, 15);
insert into roles_modules values (default, 3, 3, 15);
insert into roles_modules values (default, 3, 4, 15);
insert into roles_modules values (default, 3, 5, 15);
insert into roles_modules values (default, 3, 12, 15);
insert into roles_modules values (default, 3, 15, 15);

---> roles_users

insert into roles_users values (default, 1, 1);
insert into roles_users values (default, 3, 2);