package net.hpclab.cev.enums;

public enum AuthenticateEnum {
	DB_INIT_ERROR, LOGIN_ERROR, LOGIN_SUCCESS, LOGIN_INVALID_FORMAT_ERROR, LOGIN_UNKNOWN_ERROR, LOGIN_USER_NOT_ACTIVE_ERROR, LOGIN_USER_LOGGED_IN_ERROR, LOGIN_RESTART_PASSWORD
}
