package net.hpclab.cev.enums;

public enum OutcomeEnum {
    CREATE_SUCCESS, UPDATE_SUCCESS, DELETE_SUCCESS,
    CREATE_ERROR, UPDATE_ERROR, DELETE_ERROR,
    FILE_REQUIRED, FILE_UPLOAD_SUCCESS, FILE_DELETE_SUCCESS, FILE_UPLOAD_ERROR, FILE_DELETE_ERROR,
    GENERIC_ERROR, GENERIC_INFO, GENERIC_WARNING,
    SELECT_NOT_GRANTED, UPDATE_NOT_GRANTED, DELETE_NOT_GRANTED, INSERT_NOT_GRANTED
}
